name: deploy

# releases 브랜치에 push 이벤트 발생 시 트리거
on:
  push:
    branches:
      - production

# 이벤트 트리거시 수행할 작업
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      # https://github.com/actions/checkout
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          repository: amuse1991/learn_FP
          ref: production
      # This action allows caching dependencies and build outputs to improve workflow execution time.
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp \
          --region ap-northeast-2 \
          --recursive \
          out s3://learnfp/
